nelmio_api_doc:
    documentation:
        info:
            title: Mon API Symfony
            description: Documentation auto-générée de l’API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
