nelmio_api_doc:
    documentation:
        openapi: 3.1.0
        info:
            title: Mon API Symfony
            description: Documentation auto-générée de l’API
            version: 1.0.0
        components:
            securitySchemes: {}
    areas:
        path_patterns:
            - ^/api(?!/doc$)
