services:

  back:
    container_name: ESGI-pa-back
    image: ghcr.io/louis-guidez/esgi-pa-back
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    restart: always
    command: >
      sh -c "php bin/console cache:clear --env=prod &&
             php bin/console cache:warmup --env=prod &&
             php-fpm"

  db:
    image: mysql:8.0
    container_name: ESGI-pa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: ESGI-pa-nginx
    ports:
      - "81:80"
    volumes:
      - ./docker/prod/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - back
    restart: always

  rustfs:
    image: rustfs/rustfs
    container_name: rustfs
    ports:
      - "9000:9000"
    volumes:
      - rustfs_data:/data
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_STORAGE_DIR: /data
      RUSTFS_API_PORT: 9000
    restart: always

volumes:
  db_data:
  rustfs_data: